version: '2'

networks:
  default:
    external:
      name: my_net
      
services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust


  jobs:
    depends_on:
      - 'postgres'
      - 'banking'
    build:
      context: ./banking
      dockerfile: Dockerfile
    command: bash start_jobs
    volumes:
      - '.:/banking'
    volumes_from:
      - box

  banking:
    depends_on:
      - 'postgres'
    build:
      context: ./banking
      dockerfile: Dockerfile
    command: bash start.sh
    ports:
      - '3001:3000'
    volumes:
      - '.:/banking'
    volumes_from:
    - box
    env_file:
      - ./.env

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box: